import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Providers from '@/lib/providers/QueryProvider';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import '@/styles/globals.css';
import ScrollTop from '@/components/layout/ScrollTop';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='ko'
      suppressHydrationWarning
    >
      <link
        rel='icon'
        href='/icons/logo-fullname.png'
        sizes='any'
      />
      <body className={`${pretendard.variable} flex flex-col min-h-screen antialiased bg-background text-foreground`}>
        <Providers>
          <Header />
          <main className='flex-1'>{children}</main>
          <Footer />
        </Providers>
        <ScrollTop />
      </body>
    </html>
  );
}
